// Generated by scripts/pack-model.mjs from joshua-xl.glb (sha256 ca99725a9c3cf3772d6234f10f64cb9c8fb71b6f5d4beb0336eff89c12559b8c).
// Do not edit; rerun the script after re-exporting the source model.
export const PACKED_MODEL_URL = '/models/candidates/joshua-xl.b20054a33657.packed.glb';
