#!/usr/bin/env node
// Derive the delivered console models from the sourced GLB. The source file is
// never modified; it stays the reference for layout tests and the source preview.
//
//   node scripts/pack-model.mjs [public/models/candidates/joshua-xl.glb]
//
// 1. gltfpack without quantization (-noq) merges identical vertices, reorders
//    triangles for the vertex cache and meshopt-compresses them. Every vertex
//    keeps the source's decoded float values; node, mesh and material names,
//    extras, unused vertex attributes and images are kept (mesh names are
//    restored afterwards).
// 2. meshopt-exp-lossless.mjs re-encodes float streams with the exponential
//    filter and v1 codec only where Three.js decodes the identical bytes.
// No texture is resized or re-encoded. The output is content-hashed for
// immutable caching, and its URL is written to src/scene/model-delivery.ts.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const GLTFPACK = 'gltfpack@1.3.0';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, process.argv[2] ?? 'public/models/candidates/joshua-xl.glb');
const directory = dirname(source), stem = basename(source, '.glb');
const scratch = mkdtempSync(join(tmpdir(), 'pack-model-'));
try {
  const unfiltered = join(scratch, 'unfiltered.glb'), packed = join(scratch, 'packed.glb');
  execFileSync('npx', ['-y', GLTFPACK, '-i', source, '-o', unfiltered, '-noq', '-cc', '-kn', '-km', '-ke', '-kv'], { stdio: 'inherit' });
  execFileSync(process.execPath, [join(root, 'scripts/restore-glb-names.mjs'), source, unfiltered], { stdio: 'inherit' });
  execFileSync(process.execPath, [join(root, 'scripts/meshopt-exp-lossless.mjs'), unfiltered, packed], { stdio: 'inherit' });
  // Remove earlier derived outputs of this source before writing the new ones.
  for (const file of readdirSync(directory)) if (new RegExp(`^${stem}\\.[0-9a-f]{12}\\.packed\\.glb$`).test(file)) rmSync(join(directory, file));
  const deliver = (file, kind) => {
    const hash = createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 12);
    const name = `${stem}.${hash}.${kind}.glb`;
    copyFileSync(file, join(directory, name));
    return '/' + join(directory, name).slice(resolve(root, 'public').length + 1).split('\\').join('/');
  };
  const urls = { packed: deliver(packed, 'packed') };
  const sourceHash = createHash('sha256').update(readFileSync(source)).digest('hex');
  writeFileSync(join(root, 'src/scene/model-delivery.ts'), `// Generated by scripts/pack-model.mjs from ${stem}.glb (sha256 ${sourceHash}).
// Do not edit; rerun the script after re-exporting the source model.
export const PACKED_MODEL_URL = '${urls.packed}';
`);
  console.log(JSON.stringify({ source: source.slice(root.length + 1), sourceSha256: sourceHash, ...urls }, null, 1));
} finally { rmSync(scratch, { recursive: true, force: true }); }
