#!/usr/bin/env node
// Derive the delivered console models from the sourced GLB. The source file is
// never modified; it stays the reference for layout tests and the source preview.
//
//   node scripts/pack-model.mjs [public/models/candidates/joshua-xl.glb]
//
// 1. packed:  gltfpack re-orders and meshopt-compresses geometry. Positions, UVs
//             and normals stay float; tangents become 8-bit normalized (gltfpack's
//             limit). Node, mesh and material names, extras and images are kept
//             (mesh names are restored from the source afterwards).
// 2. compact: packed, with textures above 2048 px halved (limit-glb-textures.mjs)
//             for drawing buffers that cannot sample the 4096 px mip level.
// Outputs are content-hashed for immutable caching, and the URLs are written to
// src/scene/model-delivery.ts.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const GLTFPACK = 'gltfpack@1.3.0';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, process.argv[2] ?? 'public/models/candidates/joshua-xl.glb');
const directory = dirname(source), stem = basename(source, '.glb');
const scratch = mkdtempSync(join(tmpdir(), 'pack-model-'));
try {
  const packed = join(scratch, 'packed.glb'), compact = join(scratch, 'compact.glb');
  execFileSync('npx', ['-y', GLTFPACK, '-i', source, '-o', packed, '-cc', '-kn', '-km', '-ke', '-vpf', '-vtf', '-vnf'], { stdio: 'inherit' });
  execFileSync(process.execPath, [join(root, 'scripts/restore-glb-names.mjs'), source, packed], { stdio: 'inherit' });
  execFileSync(process.execPath, [join(root, 'scripts/limit-glb-textures.mjs'), packed, compact, '--max', '2048', '--quality', '92'], { stdio: 'inherit' });
  // Remove earlier derived outputs of this source before writing the new ones.
  for (const file of readdirSync(directory)) if (new RegExp(`^${stem}\\.[0-9a-f]{12}\\.(packed|compact)\\.glb$`).test(file)) rmSync(join(directory, file));
  const deliver = (file, kind) => {
    const hash = createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 12);
    const name = `${stem}.${hash}.${kind}.glb`;
    copyFileSync(file, join(directory, name));
    return '/' + join(directory, name).slice(resolve(root, 'public').length + 1).split('\\').join('/');
  };
  const urls = { packed: deliver(packed, 'packed'), compact: deliver(compact, 'compact') };
  const sourceHash = createHash('sha256').update(readFileSync(source)).digest('hex');
  writeFileSync(join(root, 'src/scene/model-delivery.ts'), `// Generated by scripts/pack-model.mjs from ${stem}.glb (sha256 ${sourceHash}).
// Do not edit; rerun the script after re-exporting the source model.
export const PACKED_MODEL_URL = '${urls.packed}';
export const COMPACT_MODEL_URL = '${urls.compact}';
`);
  console.log(JSON.stringify({ source: source.slice(root.length + 1), sourceSha256: sourceHash, ...urls }, null, 1));
} finally { rmSync(scratch, { recursive: true, force: true }); }
